name: backend server build
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "docker version to release"

env:
  REGISTRY: ghcr.io
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.17
#      -
#        name: Login to GithubPackages
#        uses: docker/login-action@v2
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: sbt universal:packageBin && cp target/universal/app-*.zip
      -
        name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # change tag
          #tags: ${{ env.REGISTRY }}/fornetcode/backend:${{github.event.inputs.version}}, ${{ env.REGISTRY }}/fornetcode/backend:latest
#      - name: Upload jar to artifact
#        uses: actions/upload-artifact@v2
#        with:
#          path: release/*
#          name: backend
#          if-no-files-found: error